---

# this playbook sets up the host with the plex media server

- hosts: all
  sudo: true
  user: ansible

  roles:
    - role: epel
    - role: selinux
    - role: firewalld
    - role: zfs
    - { role: transmission, tags: ['transmission'] }
    - { role: plex, tags: ['plex'] }

  vars:
    plexdatastore: /data/plex
    plexsetup: https://downloads.plex.tv/plex-media-server/0.9.9.14.531-7eef8c6/plexmediaserver-0.9.9.14.531-7eef8c6.x86_64.rpm
    plexlibraries:
      - "{{ plexdatastore }}/public/movies"
      - "{{ plexdatastore }}/public/tv"
      - "{{ plexdatastore }}/public/music"
      - "{{ plexdatastore }}/public/photos"
      - "{{ plexdatastore }}/public/homevideos"
    transmissionroot: /data/transmission
    blocklist: http://john.bitsurge.net/public/biglist.p2p.gz
    transmissiondirectories:
      - "{{ transmissionroot }}/downloads"
      - "{{ transmissionroot }}/incomplete"