---

# this playbook sets up the host with the plex media server

- hosts: all
  sudo: true
  user: ansible

  roles:
    - { role: yum, tags: ['yum'] }
    - { role: epel, tags: ['epel'] }
    - { role: rpmforge, tags: ['rpmforge'] }
    - { role: selinux, tags: ['selinux'] }
    - { role: firewalld, tags: ['firewalld'] }
    - { role: duckdns, tags: ['duckdns'] }
    - { role: zfs, tags: ['zfs'] }
    - { role: nzbtomedia, tags: ['nzbtomedia'] }
    - { role: transmission, tags: ['transmission'] }
    - { role: plex, tags: ['plex'] }
    - { role: couchpotato, tags: ['couch'] }
    - { role: sickbeard, tags: ['beard'] }
    - { role: sabnzbd, tags: ['sabnzbd'] }
    - { role: httpd, tags: ['httpd'] }
    - { role: rssdler, tags: ['rssdler'] }
    #- { role: mysql, tags: ['mysql'] }
    #- { role: newznab, tags: ['newznab'] }