---

- name: install avahi
  dnf:
    name={{item}}
    state=present
  with_items:
    - avahi
    - nss-mdns
  tags:
    - setup
    - avahi

- name: enable and start avahi
  service:
    name=avahi-daemin
    state=started
    enable=yes
