transmissionroot: /data/transmission
blocklist: http://john.bitsurge.net/public/biglist.p2p.gz
transmissiondirectories:
  - "{{ transmissionroot }}/downloads"
  - "{{ transmissionroot }}/incomplete"
username: barfoot
password: barfoot
rcpwhitelist: "127.0.0.1,192.168.88.0/24"