---
transmissionroot: /data/transmission
remoteblocklists: 
#  - "http://john.bitsurge.net/public/biglist.p2p.gz"
  - "http://list.iblocklist.com/?list=ch&fileformat=p2p&archiveformat=zip"
  - "http://list.iblocklist.com/?list=ydxerpxkpcfqjaybcssw&fileformat=p2p&archiveformat=zip"
  - "http://list.iblocklist.com/?list=dufcxgnbjsdwmwctgfuj&fileformat=p2p&archiveformat=zip"
#localblocklists:
#  - ""
transmissiondirectories:
  - "{{ transmissionroot }}/downloads"
  - "{{ transmissionroot }}/downloads/tv"
  - "{{ transmissionroot }}/downloads/movies"
  - "{{ transmissionroot }}/incomplete"
  - "{{ transmissionroot }}/blackhole"
username: barfoot
password: barfoot
rcpwhitelist: "127.0.0.1,192.168.88.0/24"
transmissionconfig: /var/lib/transmission/.config/transmission-daemon
queue: "{{ transmissionconfig }}/torrents/"
blocklistdir: "{{ transmissionconfig }}/blocklists/"