---

# directory which containes the websites served
# up by the local nginx container
dnas_html: /var/dnas/html

dnas_nfs:
  server: 192.168.88.17
  path: /mnt/test/test/nfs
  mount: /mnt/nfs
  opts: rw,sync,nolock
  type: nfs

# docker container information for couchpotato
dnas_container_couchpotato:
  ports:
    - "5050:5050"
  volumes:
    - /mnt/nfs/docker/couchpotato/cache:/home/couchpotato/cache
    - /mnt/nfs/docker/couchpotato/custom_plugins:/home/couchpotato/custom_plugins
    - /mnt/nfs/docker/couchpotato/database:/home/couchpotato/database
    - /mnt/nfs/docker/couchpotato/db_backup:/home/couchpotato/db_backup
    - /mnt/nfs/docker/couchpotato/logs:/home/couchpotato/logs
    - /mnt/nfs/library:/library
    - /mnt/nfs/docker/sabnzbd/incomplete:/home/sabnzbd/Downloads/incomplete
    - /mnt/nfs/docker/sabnzbd/complete:/home/sabnzbd/Downloads/complete
    - /home/couchpotato
  uid: 5002
  gid: 5002
  restart: always
  #config: https://raw.githubusercontent.com/sebastianhutter/dnas/master/container/couchpotato/build/settings.conf
  config: http://192.168.88.240/settings.conf

dnas_container_couchpotato_command:
  "-c couchpotato -q -n -m -f {{dnas_container_couchpotato.config}} -i {{dnas_container_couchpotato.uid}} -o {{dnas_container_couchpotato.gid}}"


# docker container information for sickrage
dnas_container_sickrage:
  ports:
    - "8081:8081"
  volumes:
    - /mnt/nfs/docker/sickbeard/data:/home/sickbeard/data
    - /mnt/nfs/library:/library
    - /home/sickbeard
    - /mnt/nfs/docker/sabnzbd/incomplete:/home/sabnzbd/Downloads/incomplete
    - /mnt/nfs/docker/sabnzbd/complete:/home/sabnzbd/Downloads/complete
  uid: 5004
  gid: 5004
  restart: always
  #config:  https://raw.githubusercontent.com/sebastianhutter/dnas/master/container/sickbeard/build/config.ini
  config: http://192.168.88.240/config.ini

dnas_container_sickrage_command:
  "-c sickbeard -q -n -m -f {{dnas_container_sickrage.config}} -i {{dnas_container_sickrage.uid}} -o {{dnas_container_sickrage.gid}}"


# docker container information for sabnzbt
dnas_container_sabnzbd:
  ports:
    - "8085:8085"
  volumes:
    - /mnt/nfs/docker/sabnzbd/logs:/home/sabnzbd/logs
    - /mnt/nfs/docker/sabnzbd/admin:/home/sabnzbd/admin
    - /mnt/nfs/docker/sabnzbd/incomplete:/home/sabnzbd/Downloads/incomplete
    - /mnt/nfs/docker/sabnzbd/complete:/home/sabnzbd/Downloads/complete
    - /opt/nzbtomedia
    - /home/sabnzbd
  uid: 5001
  gid: 5001
  restart: always
  #config:  https://raw.githubusercontent.com/sebastianhutter/dnas/master/container/sabnzbd/build/sabnzbd.ini
  config: http://192.168.88.240/sabnzbd.ini
  nzbtomedia_config: http://192.168.88.240/autoProcessMedia.cfg

dnas_container_sabnzbd_command:
  "-c sabnzbd -q -n -m -f {{dnas_container_sabnzbd.config}} -d {{dnas_container_sabnzbd.nzbtomedia_config}} -i {{dnas_container_sabnzbd.uid}} -o {{dnas_container_sabnzbd.gid}}"


# docker container information for plex
dnas_container_plex:
  ports:
    - "32400:32400"
    - "1900:1900/udp"
    - "3005:3005"
    - "5353:5353/udp"
    - "8324:8324"
    - "32410:32410/udp"
    - "32412:32412/udp"
    - "32413:32413/udp"
    - "32469:32469"
  volumes:
    - "/mnt/nfs/docker/plex/Plex Media Server:/var/lib/plexmediaserver/Library/Application Support/Plex Media Server"
  uid: 5003
  gid: 5003
  restart: always

dnas_container_plex_command:
  "-c plex -q -i {{dnas_container_plex.uid}} -o {{dnas_container_plex.gid}}"


# docker container which serves up a small website
# which links to the different services on the machine
dnas_container_nginx:
  ports:
    - "80:80"
  volumes:
    - "{{dnas_html}}:/usr/share/nginx/html:ro"
  restart: always

dnas_container_nginx_command:
  'nginx -g "daemon off;"'

# docker container which serves up the openvpn service
# this is the only container which automatically starts during boot
dnas_container_openvpnas:
  ports:
    - "443:443"
    - "943:943"
    - "1194:1194"
    - "1194:1993/udp"
  restart: always

dnas_container_openvpn_command:
  '-c openvpnas'