---

# directory which containes the websites served
# up by the local nginx container
dnas_html: /var/dnas/html

# directory with local volumes of containers 
# necessary for openvpn 
dnas_local: /srv/docker

# nfs mounts
dnas_nfs:
  docker:
    server: nas.barfoot.local
    path: /volume1/docker
    mount: /mnt/docker
    opts: rw,async,nolock
    type: nfs
  library:
    server: nas.barfoot.local
    path: /volume1/library
    mount: /mnt/library
    opts: rw,async,nolock
    type: nfs
  calibre:
    server: nas.barfoot.local
    path: /volume1/calibre
    mount: /mnt/calibre
    opts: rw,async,nolock
    type: nfs
  web:
    server: nas.barfoot.local
    path: /volume1/web
    mount: /mnt/web
    opts: rw,async,nolock
    type: nfs

#
# docker container defitnion
# 

dnas_environment_folder: /etc/dnas-environment

docker_containers:
  # nginx reverse proxy server
  nginx:
    name: nginx
    description: static information and reverse proxy
    use_systemd: yes
    image: sebastianhutter/nginx
    image_version: latest
    restart_policy: always
    env:
      CONFIG_URL: "http://nas.barfoot.local/dnas/docker/nginx.conf"
      CONFIG_GENERATE_SSL: "yes"
      CONFIG_SSL_SUBJ: "/C=CH/ST=Zurich/L=Zurich/O=private/OU=dockering/CN=barfoot.local"
    publish:
      - "80:80"
      - "8443:443"
  # ebook server
  #ubooquity-privat:
  #  name: ubooquity-privat
  #  description: ebook server privat
  #  use_systemd: yes
  #  image: sebastianhutter/ubooquity
  #  image_version: latest
  #  restart_policy: always
  #  env:
  #    CONFIG_URL: "http://nas.barfoot.local/dnas/docker/preferences_privat.xml"
  #  publish:
  #    - "2202:2202"
  #  volumes:
  #    - "{{dnas_nfs.calibre.mount}}:/var/lib/ubooquity"
  #ubooquity-david:
  #  name: ubooquity-david
  #  description: ebook server davids library
  #  use_systemd: yes
  #  image: sebastianhutter/ubooquity
  #  image_version: latest
  #  restart_policy: always
  #  env:
  #    CONFIG_URL: "http://nas.barfoot.local/dnas/docker/preferences_david.xml"
  #  publish:
  #    - "2203:2202"
  #  volumes:
  #    - "{{dnas_nfs.calibre.mount}}:/var/lib/ubooquity"
  calibre-privat:
    name: calibre-privat
    description: ebook server privat
    use_systemd: yes
    image: sebastianhutter/calibreserver
    image_version: latest
    restart_policy: always
    env:
      PREFIX_URL: /calibre/privat
    publish:
      - "2202:80"
    volumes:
      - "{{dnas_nfs.calibre.mount}}/personal:/library"
  calibre-david:
    name: calibre-david
    description: ebook server david
    use_systemd: yes
    image: sebastianhutter/calibreserver
    image_version: latest
    restart_policy: always
    env:
      PREFIX_URL: /calibre/david
    publish:
      - "2203:80"
    volumes:
      - "{{dnas_nfs.calibre.mount}}/davids:/library"   
  # openvpn access server
  openvpnas:
    name: openvpnas
    description: openvpn access server
    use_systemd: yes
    image: sebastianhutter/openvpnas
    image_version: latest
    restart_policy: always
    publish:
      - "443:443"
      - "943:943"
      - "1194:1194"
      - "1194:1194/udp"
    volumes:
      - "{{dnas_local}}/openvpnas:/usr/local/openvpn_as/etc"
    devices:
      - "/dev/net/tun"
    capadd:
      - "NET_ADMIN"
      - "NET_RAW"
    tty: true
    #network: host
  # podcast container defition. used to download podcasts via git - annex 
  # the container is created on a per use basis - no systemd file
  podcatcher:
    name: podcatcher
    description: podcast downloader based on git-annex
    use_systemd: no
    image: sebastianhutter/podcatcher
    image_version: latest
    restart_policy: "no"
    env:
      AUTHURL: http://nas.barfoot.local/dnas/docker/netrc
      PODCASTSURL: http://nas.barfoot.local/dnas/docker/podcasts
      ANNEXMODE: direct
    volumes:
      - "{{dnas_nfs.docker.mount}}/podcasts/config:/volumes/config"
      - "{{dnas_nfs.library.mount}}/podcasts:/volumes/podcasts"
    tty: true
  # sonarr - tv downloading etc
  sonarr:
    name: sonarr
    description: sonarr tv downloader
    use_systemd: yes
    image: linuxserver/sonarr
    image_version: latest
    restart_policy: always
    publish:
      - "8989:8989"
    volumes:
      - "{{dnas_nfs.docker.mount}}/sabnzbd/complete:/sabnzbd/Downloads/complete"
      - "{{dnas_nfs.docker.mount}}/sonarr/config:/config"
      #- "{{dnas_nfs.docker.mount}}/sonarr/media:/volumes/media"
      - "{{dnas_nfs.library.mount}}/tv:/tv"
      - "{{dnas_nfs.library.mount}}/tv_de:/tv_de"
      - "/dev/rtc:/dev/rtc:ro"
    tty: true
  # sabnzbd new image 
  sabnzbd2:
    name: sabnzbd2
    description: sabnzbd usenet downloader
    use_systemd: yes
    image: sebastianhutter/sabnzbd
    image_version: latest
    restart_policy: always
    env:
      SABNZBD_CONFIG_URL: "http://nas.barfoot.local/dnas/docker/sabnzbd.ini"
      NZBTOMEDIA_CONFIG_URL: "http://nas.barfoot.local/dnas/docker/autoProcessMedia.cfg"
    publish:
      - "8085:8085"
    volumes:
      - "{{dnas_nfs.docker.mount}}/sabnzbd/logs:/sabnzbd/logs"
      - "{{dnas_nfs.docker.mount}}/sabnzbd/admin:/sabnzbd/admin"
      - "{{dnas_nfs.docker.mount}}/sabnzbd/incomplete:/sabnzbd/Downloads/incomplete"
      - "{{dnas_nfs.docker.mount}}/sabnzbd/complete:/sabnzbd/Downloads/complete"
    tty: true
  # couchpotato new image
  couchpotato2:
    name: couchpotato2
    description: couchpotato movie downloader
    use_systemd: yes
    image: sebastianhutter/couchpotato
    image_version: latest
    restart_policy: always
    env:
      COUCHPOTATO_CONFIG_URL: "http://nas.barfoot.local/dnas/docker/settings.conf"
    publish:
      - "5050:5050"
    volumes:
      - "{{dnas_nfs.docker.mount}}/couchpotato/cache:/CouchPotatoServer/cache"
      - "{{dnas_nfs.docker.mount}}/couchpotato/custom_plugins:/CouchPotatoServer/custom_plugins"
      - "{{dnas_nfs.docker.mount}}/couchpotato/database:/CouchPotatoServer/database"
      - "{{dnas_nfs.docker.mount}}/couchpotato/db_backup:/CouchPotatoServer/db_backup"
      - "{{dnas_nfs.docker.mount}}/couchpotato/logs:/CouchPotatoServer/logs"
      - "{{dnas_nfs.library.mount}}:/library"
      - "{{dnas_nfs.docker.mount}}/sabnzbd/incomplete:/sabnzbd/Downloads/incomplete"
      - "{{dnas_nfs.docker.mount}}/sabnzbd/complete:/sabnzbd/Downloads/complete"
    tty: true
  # temporary squiid proxy
  squid:
    name: squid
    description: squid web proxy
    use_systemd: yes
    image: sameersbn/squid
    image_version: 3.3.8-14
    restart_policy: always
    env:
      SQUID_CONFIG_URL: "http://nas.barfoot.local/dnas/docker/squid.conf"
    publish:
      - "3128:3128"
    volumes:
      - "{{dnas_local}}/squid/squid.conf:/etc/squid3/squid.conf"
    tty: true
    custom_execstartpre:
      - "/usr/bin/curl -o {{dnas_local}}/squid/squid.conf $SQUID_CONFIG_URL"
  jenkins:
    name: jenkins
    description: jenkins container
    use_systemd: yes
    image: sebastianhutter/jenkins
    image_version: latest
    restart_policy: always
    publish:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "{{dnas_nfs.docker.mount}}/jenkins:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    tty: true
    user: root

#
# cronjobs and scripts
#

# ip denial script for mikrotik
dnas_denial_count: 15
dnas_denial_text_file: "{{dnas_nfs.web.mount}}/dnas/docker/ip_address_drop.rsc"
