---

- name: create sabnzbd user
  user: createhome=yes home=/var/lib/sabnzbd name=sabnzbd shell=/sbin/nologin state=present system=yes

- name: download the sabnzbd source
  git: repo=https://github.com/sabnzbd/sabnzbd.git dest=/opt/sabnzbd

- name: change owner of the sabnzbd source files
  file: path=/opt/sabnzbd owner=sabnzbd group=sabnzbd recurse=yes

- name: copy systemd configuration
  template: src=sabnzbd.service.j2 dest=/etc/systemd/system/sabnzbd.service

- name: enable sabnzbd
  service: name=sabnzbd state=started enabled=yes