---

#
# default configuration for linux hosts
#

# create additional local user with sudo rights 
## which variables could i use for that task?
- name: create local user for administrative access
  user: name=sysprog comment="administrative user account" 
          password=$6$rounds=40000$VNQYBHdL90ev0M/n$MmWR26FLzZvfpX/Z5ViQ89hq6APCBd7zDmMryYkt6sya.zHAXGgKPubl01qtzhdUlAavKEToxT1JBbF9N5AFa1
          state=present

# add public key for the user 
- name: add public key for the sysprog user
  authorized_key: user=sysprog key="{{ lookup('file', 'sysprog.pub') }}"

# set the sudoers file for the user
- name: copy sudoers.d file for administrative user account
  copy: src=sudoers_sysprog dest=/etc/sudoers.d/sysprog owner=root group=root 
          mode=644 backup=yes

# if it is a redhat based machine install the epel repositories
- name: install the epel repository if its a redhat based machine
  yum: name=http://dl.fedoraproject.org/pub/epel/6/{{ ansible_architecture }}/epel-release-6-8.noarch.rpm state=present
  when: ansible_os_family == "RedHat"

# do a full system update
- name: update the system (redhat)
  yum: name=* state=latest
  when: ansible_os_family == "RedHat"

- name: update the system (Debian)
  apt: upgrade=dist
  when: ansible_os_family == "Debian"

# now install some default software packages
- name: install must have software (redhat)
  yum: name={{ item }} state=latest
  with_items:
    - nc
    - subversion
    - git
  when: ansible_os_family == "RedHat"

# reconfigure sshd
- name: reconfigure sshd daemon
  copy: src=sshd_config dest=/etc/ssh/ backup=yes owner=root group=root mode=600
  notify:
  - restart sshd 

# copy banner to host
- name: copy banner (issue) to node
  copy: src=issue dest=/etc/ backup=yes owner=root group=root mode=644

# copy dynamic motd script to the node
- name: copy dynamic motd to the node
  copy: src=dynmotd dest=/usr/local/bin owner=root group=root mode=755

# enable dynamic pseudo motd for every user who logs in
- name: enable dynmotd script
  lineinfile: dest=/etc/profile backup=yes state=present line=/usr/local/bin/dynmotd


#disable ctrl+lt+delete in the console 
# before the override configuration is copied check if the control alt del
# configuration on the host exists
- name: check if the control-alt-delete configuration exists
  command: /usr/bin/test -e /etc/init/control-alt-delete.conf
  register: ctrlexists
  ignore_errors: True

- name: copy the ctrl-alt-delete override configuration
  copy: src=control-alt-delete.override dest=/etc/init/control-alt-delete.override owner=root group=root 
  when: ctrlexists|success

# disable ipv6
- name: disable ipv6
  lineinfile: dest=/etc/sysconfig/network backup=yes state=present line=NETWORKING_IPV6=no
  lineinfile: dest=/etc/sysconfig/network state=present line=IPV6INIT=no 

