---

#
# install postgresql 9.4 on the host
#

- name: install the postgresql repository
  yum: name=http://yum.pgrpms.org/9.4/redhat/rhel-6-{{ ansible_architecture }}/pgdg-centos94-9.4-1.noarch.rpm state=present
  when: ansible_os_family == "RedHat"

- name: install necessary packages
  yum: state=latest name={{ item }}
  with_items:
    - postgresql94-server
    - postgresql94-plperl
    - postgresql94-contrib
    - postgresql94-devel
    - postgresql94

- name: add postgresql to path
  copy: src=pgsql_path.sh dest=/etc/profile.d/pgsql_path.sh owner=root group=root mode=0644 backup=yes 

#
## configure postgresql
#

- name: initiate postgresql database
  command: service postgresql-9.4 initdb 

- name: replace the default postgresql timezone with UTC
  template: backup=yes src=postgresql.conf.j2 dest=/var/lib/pgsql/9.4/data/postgresql.conf  
            owner=postgres group=postgres mode=0600
  notify: restart postgresql

- name: set the default authentication method to md5
  template: backup=yes src=pg_hba.conf.j2 dest=/var/lib/pgsql/9.4/data/pg_hba.conf  
            owner=postgres group=postgres mode=0600
  notify: restart postgresql

- name: (auto)start postgresql service
  service: state=started enabled=yes name=postgresql-9.4