---
#
# adclient role tasks
#

- name: check if the service file for pbis exists
  command: /usr/bin/test -e /etc/init.d/lwsmd
  register: installed
  ignore_errors: True

- name: install pbis open edition on redhat systems
  script: pbis-open-8.0.1.2029.linux.{{ ansible_architecture }}.rpm.sh --nox11 -- install
  when: ansible_os_family == "RedHat" and installed|failed

- name: install pbis open edition on debian systems
  script: pbis-open-8.0.1.2029.linux.{{ ansible_architecture }}.deb.sh --nox11 -- install 
  when: ansible_os_family == "Debian" and installed|failed

# join the domain defined in the credentials vault
- name: join the active directory
  pbis: domain={{ domain }} domuser={{ username }} dompass={{ password }} 
  when: orgunit is not defined 

# join the domain defined in the credentials vault if an ou is specified
- name: join the active directory into specific OU
  pbis: domain={{ domain }} domuser={{ username }} dompass={{ password }} ou={{ orgunit }} 
  when: orgunit is defined

# now after the domain join add the domain groups to be allowed to access ssh