---

# install the transmission daemon
- name: install plex
  yum: state=present name={{ plexsetup }}

- name: install git
  yum: state=latest name=git

- name: create library directories 
  file: dest={{ item }} state=directory owner=plex group=plex mode=2775
  with_items: plexlibraries

# for the acls to work you need to enable them on the zfs
# pool
# zfs set acltype=posixacl <pool>
- name: set acls on library directories
  command: setfacl -R -d -m u:plex:rwx,g:plex:rwx {{ item }}
  with_items: plexlibraries


# Run the command if the specified file does not exist.
- command: /usr/bin/make_database.sh arg1 arg2 creates=/path/to/database

- name: create cache directory
  file: dest="{{ plexdatastore }}/Application Support" state=directory owner=plex group=plex mode=0775

#- name: link cache directory
#  file: state=link owner=plex group=plex src="{{ plexdatastore }}/Application Support" dest="/var/lib/plexmediaserver/Library/Application Support"

- name: enable and start plex 
  service: name=plexmediaserver state=started enabled=yes




#- name: install the inofficial appstore bundle
#  #unarchive: copy=yes src=UnSupportedAppstore.bundle.zip dest='/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins'
#  # was not able to escabe the spaces in the full path to the plex plugin dir.
#  unarchive: copy=yes src=UnSupportedAppstore.bundle.zip dest=/tmp/

#- name: set filepermissions on appstore bundle
#  file: state=directory mode=775 owner=plex group=plex path=/tmp/UnSupportedAppstore.bundle recurse=yes

#- name: move inofficial appstore bundle
#  command: mv -u -f /tmp/UnSupportedAppstore.bundle /var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server/Plug-ins/
#  ignore_errors: yes

#- name: move plexmedia chache directory

#- name: install node.js and pip for spotify bundle
#  yum: name={{ item }} state=latest
#  with_items:
#  - nodejs 
#  - npm
#  - python-pip

#- name: install pyexecjs for spotify2
#  pip: name=pyexecjs state=latest
